ZADANIE_DOMOWE/app/models.py
from app import db
from flask_login import UserMixin

class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(150), nullable=False, unique=True)
    email = db.Column(db.String(150), nullable=False, unique=True)
    password = db.Column(db.String(150), nullable=False)
    role = db.Column(db.String(50), nullable=False, default='User')
    tasks = db.relationship('Task', backref='owner', lazy=True)

class Task(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(150), nullable=False)
    description = db.Column(db.Text, nullable=True)
    deadline = db.Column(db.DateTime, nullable=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)

ZADANIE_DOMOWE/app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, BooleanField, TextAreaField, DateTimeLocalField, SelectField
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError
from flask_ckeditor import CKEditorField
from werkzeug.security import check_password_hash
from app.models import User

class RegistrationForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired(), Length(min=2, max=20)])
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    password2 = PasswordField('Confirm Password', validators=[DataRequired(), EqualTo('password', message='Password must match!')])
    # role = SelectField('Role', choices=[('user', 'User'), ('admin', 'Admin')], validators=[DataRequired()])
    role = StringField('Role', default='User')
    submit = SubmitField('Sign Up')

class LoginForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired(), Length(min=2, max=20)])
    password = PasswordField('Password', validators=[DataRequired()])
    remember_me = BooleanField('Remember Me')
    submit = SubmitField('Login')

    def validate_password(self, field):
        user = User.query.filter_by(username=self.username.data).first()
        if user and not check_password_hash(user.password, field.data):
            raise ValidationError('Incorrect password')

class TaskForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    description = CKEditorField('Description')
    deadline = DateTimeLocalField('Deadline', format='%Y-%m-%dT%H:%M')
    submit = SubmitField('Submit')

ZADANIE_DOMOWE/app/__init__.py
from flask import Flask
from flask_ckeditor import CKEditor
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from .config import Config

db = SQLAlchemy()
login_manager = LoginManager()
ckeditor = CKEditor()

def create_app():
    app = Flask(__name__)
    app.config.from_object(Config)

    db.init_app(app)
    login_manager.init_app(app)
    login_manager.login_view = 'auth.log_in'

    from app.blueprints.auth import auth_bp
    from app.blueprints.tasks import tasks_bp
    from app.blueprints.admin import admin_bp  
    app.register_blueprint(auth_bp)
    app.register_blueprint(tasks_bp)
    app.register_blueprint(admin_bp)  

    from app.models import User
    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(int(user_id))

    return app

ZADANIE_DOMOWE/app/blueprints/admin.py
from flask import Blueprint, render_template
from flask_login import login_required, current_user
from app.models import Task, User
from functools import wraps
from flask import abort

admin_bp = Blueprint('admin', __name__)

def role_required(role): 
    def decorator(func): 
        @wraps(func) 
        def decorated_view(*args, **kwargs):
            if not current_user.is_authenticated or current_user.role != 'admin': 
                abort(403) 
            return func(*args, **kwargs) 
        return decorated_view
    return decorator

@admin_bp.route('/admin')
@login_required
@role_required('admin')
def admin():
    return f'Hello Admin {current_user.username}!'

ZADANIE_DOMOWE/app/blueprints/auth.py
from flask import Blueprint, render_template, redirect, url_for, flash, request
from app.forms import LoginForm, RegistrationForm
from app.models import User
from app import db
from werkzeug.security import check_password_hash, generate_password_hash
from flask_login import login_user, logout_user, login_required

auth_bp = Blueprint('auth', __name__)

@auth_bp.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = generate_password_hash(form.password.data, method='pbkdf2')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password, role=form.role.data)
        db.session.add(user)
        db.session.commit()
        login_user(user)
        return redirect(url_for('tasks.list_tasks'))
    return render_template('register.html', form=form)

@auth_bp.route('/log_in', methods=['GET', 'POST'])
def log_in():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and check_password_hash(user.password, form.password.data):  
            login_user(user, remember=form.remember_me.data)
            next_page = request.args.get('next')
            return redirect(next_page or url_for('tasks.list_tasks'))
        else:
            flash('Login Unsuccessful. Please check username and password', 'danger')
    return render_template('login.html', form=form)

@auth_bp.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('tasks.index'))

ZADANIE_DOMOWE/app/blueprints/tasks.py
from flask import Blueprint, render_template, redirect, url_for, flash, request
from app.forms import TaskForm
from app.models import Task
from app import db
from flask_login import login_required, current_user

tasks_bp = Blueprint('tasks', __name__)

@tasks_bp.route('/')
def index():
    return render_template('index.html')

@tasks_bp.route('/tasks')
@login_required
def list_tasks():
    tasks = Task.query.filter_by(user_id=current_user.id).all()
    return render_template('list_tasks.html', tasks=tasks)

@tasks_bp.route('/tasks/new', methods=['GET', 'POST'])
@login_required
def create_task():
    form = TaskForm()
    if form.validate_on_submit():
        task = Task(
            title=form.title.data, 
            description=form.description.data, 
            deadline=form.deadline.data, 
            user_id=current_user.id)
        db.session.add(task)
        db.session.commit()
        return redirect(url_for('tasks.list_tasks'))
    return render_template('create_task.html', form=form)

@tasks_bp.route('/tasks/<int:task_id>/edit', methods=['GET', 'POST'])
@login_required
def edit_task(task_id):
    task = Task.query.get_or_404(task_id)
    if task.owner != current_user:
        return redirect(url_for('tasks.list_tasks'))
    form = TaskForm()
    if form.validate_on_submit():
        task.title = form.title.data
        task.description = form.description.data
        task.deadline = form.deadline.data
        db.session.commit()
        return redirect(url_for('tasks.list_tasks'))
    elif request.method == 'GET':
        form.title.data = task.title
        form.description.data = task.description
        form.deadline.data = task.deadline
    return render_template('edit_task.html', form=form)

@tasks_bp.route('/open/<int:task_id>/open')
@login_required
def open_task(task_id):
    task = Task.query.get_or_404(task_id)
    if task.owner != current_user:
        flash('You are not authorized to delete this task.', 'danger')
        return redirect(url_for('tasks.list_tasks'))
    return render_template('open_task.html', task=task)

@tasks_bp.route('/tasks/<int:task_id>/delete', methods=['POST'])
@login_required
def delete_task(task_id):
    task = Task.query.get_or_404(task_id)
    if task.owner != current_user:
        flash('You are not authorized to delete this task.', 'danger')
        return redirect(url_for('tasks.list_tasks'))
    db.session.delete(task)
    db.session.commit()
    flash('Task has been deleted.', 'success')
    return redirect(url_for('tasks.list_tasks'))

@tasks_bp.route('/all_tasks')
@login_required
def all_tasks():
    if current_user.role == 'admin':
        tasks = Task.query.all()
        return render_template('all_tasks.html', tasks=tasks)
    else:
        flash('You do not have permission to access this page.', 'danger')
        return redirect(url_for('tasks.list_tasks'))

ZADANIE_DOMOWE/app/templates/all_tasks.html
{% extends 'base.html' %}

{% block title %}All Tasks{% endblock %}

{% block content %}
<h1>All Tasks</h1>
<table class="table">
    <thead>
        <tr>
            <th>Title</th>
            <th>Description</th>
            <th>Deadline</th>
            <th>User</th>
        </tr>
    </thead>
    <tbody>
        {% for task in tasks %}
        <tr>
            <td>{{ task.title }}</td>
            <td>{{ task.description|safe }}</td>
            <td>{{ task.deadline }}</td>
            <td>{{ task.owner.username }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

ZADANIE_DOMOWE/app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}To-Do App{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <ul class="navbar-nav ml-auto d-flex flex-row">
            {% if current_user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link mr-3" href="{{ url_for('tasks.list_tasks') }}">My Tasks</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link mr-3" href="{{ url_for('auth.logout') }}">Logout</a>
                </li>
                {% if current_user.role == 'admin' %}
                    <li class="nav-item">
                        <a class="nav-link mr-3" href="{{ url_for('tasks.all_tasks') }}">See All Tasks</a>
                    </li>
                {% endif %}
            {% else %}
                <li class="nav-item">
                    <a class="nav-link mr-3" href="{{ url_for('auth.log_in') }}">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('auth.register') }}">Register</a>
                </li>
            {% endif %}
        </ul>
    </nav>
    <div class="container">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

ZADANIE_DOMOWE/app/templates/create_task.html
{% extends 'base.html' %}

{% block title %}Create Task{% endblock %}

{% block content %}
<h1>Create Task</h1>
<form method="POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
        {{ form.title.label }}
        {{ form.title(class="form-control") }}
    </div>
    <div class="form-group">
        {{ form.description.label }}
        {{ form.description(class="ckeditor form-control") }}
    </div>
    <div class="form-group">
        {{ form.deadline.label }}
        {{ form.deadline(class="form-control") }}
    </div>
    <div class="form-group">
        {{ form.submit(class="btn btn-primary") }}
    </div>
</form>
<script src="https://cdn.ckeditor.com/4.16.2/standard/ckeditor.js"></script>
<script>
    CKEDITOR.replace('description');
</script>
{% endblock %}

ZADANIE_DOMOWE/app/templates/edit_task.html
{% extends 'base.html' %}

{% block title %}Edit Task{% endblock %}

{% block content %}
<h1>Edit Task</h1>
<form method="POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
        {{ form.title.label }}
        {{ form.title(class="form-control") }}
    </div>
    <div class="form-group">
        {{ form.description.label }}
        {{ form.description(class="ckeditor form-control") }}
    </div>
    <div class="form-group">
        {{ form.deadline.label }}
        {{ form.deadline(class="form-control") }}
    </div>
    <div class="form-group">
        {{ form.submit(class="btn btn-primary") }}
    </div>
</form>
<script src="https://cdn.ckeditor.com/4.16.2/standard/ckeditor.js"></script>
<script>
    CKEDITOR.replace('description');
</script>
{% endblock %}

ZADANIE_DOMOWE/app/templates/index.html
{% extends 'base.html' %}

{% block content %}
<h1>Welcome to or welcome back!</h1>
<h4>Create your own to-do list and enjoy amazing organization of your day!</h4>
<br>
<p>Remember - to create a list or make changes, you must be logged in.</p>
{% endblock %}

ZADANIE_DOMOWE/app/templates/list_tasks.html
{% extends 'base.html' %}

{% block title %}My Tasks{% endblock %}

{% block content %}
<h1>My Tasks</h1>
<table class="table">
    <thead>
        <tr>
            <th>Title</th>
            <th>Deadline</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        {% for task in tasks %}
        <tr>
            <td>{{ task.title }}</td>
            <td>{{ task.deadline }}</td>
            <td>
                <a href="{{ url_for('tasks.edit_task', task_id=task.id) }}" class="btn btn-sm btn-info">Edit</a>
                <a href="{{ url_for('tasks.open_task', task_id=task.id) }}" class="btn btn-sm btn-info">Open</a>
                <form action="{{ url_for('tasks.delete_task', task_id=task.id) }}" method="POST" style="display: inline;">
                    <button type="submit" class="btn btn-sm btn-danger">Delete</button>
                </form>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
<a href="{{ url_for('tasks.create_task') }}" class="btn btn-primary">Add Task</a>
{% endblock %}

ZADANIE_DOMOWE/app/templates/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
<h1>Login</h1>
<form method="POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
        {{ form.username.label }}
        {{ form.username(class="form-control") }}
    </div>
    <div class="form-group">
        {{ form.password.label }}
        {{ form.password(class="form-control") }}
        {% for error in form.password.errors %}
            <div class="alert alert-danger">{{ error }}</div>
        {% endfor %}
    </div>
    <div class="form-group">
        {{ form.remember_me(class="form-check-input") }}
        {{ form.remember_me.label(class="form-check-label") }}
    </div>
    <div class="form-group">
        {{ form.submit(class="btn btn-primary") }}
    </div>
</form>
{% endblock %}

ZADANIE_DOMOWE/app/templates/open_task.html
{% extends 'base.html' %}

{% block title %}My Tasks{% endblock %}

{% block content %}
<h1>My Task: {{ task.title }}</h1>
<p> {{ task.description|safe  }}</p>

{% endblock %}

ZADANIE_DOMOWE/app/templates/register.html
{% extends 'base.html' %}

{% block title %}Register{% endblock %}

{% block content %}
<h1>Register</h1>
<form method="POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
        {{ form.username.label }}
        {{ form.username(class="form-control") }}
    </div>
    <div class="form-group">
        {{ form.email.label }}
        {{ form.email(class="form-control") }}
    </div>
    <div class="form-group">
        {{ form.password.label }}
        {{ form.password(class="form-control") }}
    </div>
    <div class="form-group">
        {{ form.password2.label }}
        {{ form.password2(class="form-control") }}
        {% for error in form.password2.errors %}
            <div class="alert alert-danger">{{ error }}</div>
        {% endfor %}
    </div>
    <!-- <p>
        {{ form.role.label }}<br>
        {{ form.role() }}<br>
      </p> -->
    <div class="form-group">
        {{ form.submit(class="btn btn-primary") }}
    </div>
</form>
{% endblock %}